pipeline {
    agent any

    // 🔔 Disparador automático: revisa el repo cada 2 minutos
    triggers {
        pollSCM('H/2 * * * *')
    }

    stages {
        stage('Build & Test') {
            steps {
                // 👇 MUY IMPORTANTE: entrar a la carpeta del curso web
                dir('curso-automatizacion-web') {
                    bat 'mvn clean test'
                }
            }
        }
    }

    post {
        always {
            // Publicar resultados de tests (ruta relativa desde el workspace)
            junit 'curso-automatizacion-web/target/surefire-reports/*.xml'

            // Publicar capturas como artefactos
            archiveArtifacts artifacts: 'curso-automatizacion-web/target/screenshots/**/*.png',
                             fingerprint: true,
                             allowEmptyArchive: true
        }
    }
}
